In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

processed_path = Path("../data/processed")

amazon_pairs = pd.read_parquet(
    processed_path / "amazon_support_pairs.parquet"
)

print("Shape:", amazon_pairs.shape)
amazon_pairs.head()

Shape: (166963, 18)

,support_tweet_id,support_author,inbound_support,support_created_at,support_text,response_tweet_id,in_response_to_tweet_id,text_length,customer_tweet_id,tweet_id_customer,customer_author,customer_inbound,customer_text,customer_created_at,customer_text_clean,clean_length,mention_only,low_information
0,269,AmazonHelp,False,Wed Nov 22 09:23:01 +0000 2017,@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは...,"270,271",272,126,272,272,115770,True,amazonのfireTVstickが見れない😢,Wed Nov 22 09:14:39 +0000 2017,amazonのfireTVstickが見れない😢,24,False,False
1,273,AmazonHelp,False,Wed Nov 22 09:40:27 +0000 2017,@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました...,274,271,69,271,271,115770,True,@AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎ...,Wed Nov 22 09:30:36 +0000 2017,電話で対応してもらいましたが改良されませんでした。 保証期間も過ぎてるので買い直しになるんで...,51,False,False
2,275,AmazonHelp,False,Wed Nov 22 10:06:26 +0000 2017,@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお...,NaN,274,54,274,274,115770,True,@AmazonHelp こちらこそありがとうございました。,Wed Nov 22 09:44:04 +0000 2017,こちらこそありがとうございました。,17,False,False
3,324,AmazonHelp,False,Wed Nov 22 09:06:00 +0000 2017,@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の...,NaN,325,153,325,325,115792,True,amazonプライムビデオ、再生エラーが多いです,Wed Nov 22 08:55:35 +0000 2017,amazonプライムビデオ、再生エラーが多いです,24,False,False
4,615,AmazonHelp,False,Tue Oct 31 22:29:00 +0000 2017,@115820 I'm sorry we've let you down! Without ...,616,617,133,617,617,115820,True,Way to drop the ball on customer service @1158...,Tue Oct 31 22:16:32 +0000 2017,Way to drop the ball on customer service so pi...,61,False,False

In [3]:
intent_prototypes = {
    "DELIVERY_DELAY":
        "my package delivery is late or delayed",

    "DELIVERY_NOT_RECEIVED":
        "my package was not received or is missing",

    "DELIVERY_TRACKING":
        "where is my package tracking status",

    "DELIVERY_DRIVER_ISSUE":
        "problem with delivery driver or delivery attempt",

    "ORDER_STATUS":
        "what is the status of my order",

    "ORDER_CANCELLATION":
        "I want to cancel my order",

    "MISSING_ITEM":
        "an item is missing from my delivered order",

    "WRONG_ITEM_RECEIVED":
        "I received the wrong item",

    "RETURN_REPLACEMENT":
        "I want to return or replace a product",

    "REFUND_STATUS":
        "where is my refund",

    "ACCOUNT_ACCESS":
        "I cannot access or log into my account",

    "ACCOUNT_SECURITY":
        "my account has been hacked or compromised",

    "UNEXPECTED_CHARGE":
        "I was charged unexpectedly or charged twice",

    "CASHBACK":
        "I have not received my cashback",

    "PRODUCT_ISSUE":
        "my product is broken defective damaged or not working"
}

In [4]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

model_multi = SentenceTransformer(
    "paraphrase-multilingual-MiniLM-L12-v2"
)

c:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 855.59it/s]

In [5]:
prototype_embeddings = model_multi.encode(
    list(intent_prototypes.values()),
    normalize_embeddings=True
)

In [6]:
candidate_sample = amazon_pairs.sample(
    n=10000,
    random_state=42
).copy()

candidate_embeddings = model_multi.encode(
    candidate_sample["customer_text_clean"].tolist(),
    normalize_embeddings=True,
    show_progress_bar=True
)

Batches: 100%|██████████| 313/313 [02:24<00:00,  2.16it/s]

In [7]:
intent_candidates = {}

for i, intent in enumerate(intent_prototypes):

    similarities = cosine_similarity(
        prototype_embeddings[i].reshape(1, -1),
        candidate_embeddings
    )[0]

    top_indices = similarities.argsort()[-40:][::-1]

    result = candidate_sample.iloc[top_indices].copy()
    result["similarity"] = similarities[top_indices]

    intent_candidates[intent] = result

In [8]:
intent_candidates["DELIVERY_DELAY"][
    ["customer_text_clean", "similarity"]
].head(40)

                                      customer_text_clean  similarity
25731   hello, My package was out for delivery but now...    0.824175
34460   Thankyou. Turns out delivery is late, should b...    0.776511
97154                               Delivery date pending    0.774415
91358   Hi My package has missed two delivery dates bu...    0.755127
102504  Delivery date is already delayed. 111-2691482-...    0.747700
18142   can you update me on my delivery that was alre...    0.747494
90432   my package that was to arrive today still says...    0.740526
97237   Another expected delivery today and another de...    0.739923
31049   ich warte seit dem 4.10 auf eine Lieferung. Am...    0.724916
68726   No and no;the estimated delivery date is usele...    0.721474
20429   I wish to complain about the late delivery of ...    0.721299
95885   my package went from 2 day delivery to 6 day c...    0.719322
113848  another one of our packages is late. This time...    0.718141
38449   Two delayed packages from this week and their ...    0.714713
159067  I ordered a package on Friday to be delivered ...    0.712038
130233  I need some information regarding a package I'...    0.708570
78762   You missed by lot. Today's the delivery date. ...    0.706747
158309  The only thing was to figure out where the pac...    0.706396
57553   I have not received my package which was to be...    0.704388
113791  I have not been given any new information on w...    0.697671
38487   Crappy delivery experience today. Took a half ...    0.693343
165874  I've had two packages that were "delayed" in t...    0.689608
35843   Yep, I’ve definitely noticed more delayed pack...    0.685160
41495   Nouvelle date de livraison estimée : 2 déc. - ...    0.683919
145915  Le suivi dit qu'une date de livraison est en a...    0.683171
149917  It was due on Thursday. Has said "out for deli...    0.682709
10140   no! Don’t say my package is out for delivery a...    0.682651
103259  Package says being delivered today by 8 PM tha...    0.682397
201     The last update was on 22nd Oct saying it’s ou...    0.681436
165250  I ordered something today that had 3-5 deliver...    0.681322
118286  I was supposed to receive my package by 8:00 p...    0.680807
77165   Please, where's my order? Delivery was at 8pm ...    0.680649
19634   Someday the will deliver my package and the 2-...    0.680370
21954   no one come to home for delivering the package...    0.677863
104477  Now expected 5 Nov - 8 Nov We're sorry your pa...    0.675555
95880   Delivery from 31 Oct - 2 Nov, item on the way....    0.674428
21113   The carrier is AMZL US. Unless the delivery ar...    0.673937
39741   I have an order with the expected delivery dat...    0.672461
128484  I'm supposed to get a package today but it is ...    0.668161
118076  another package delayed. This is the 4th time ...    0.667185

In [9]:
intent_candidates["MISSING_ITEM"][
    ["customer_text_clean", "similarity"]
].head(40)

                                      customer_text_clean  similarity
32466   I am not able to return my Order. Even though ...    0.740536
70811   Order # 402-5479722-9566747, wrong item receiv...    0.735128
134422  My Order id: 403-6019015-9546740.I still haven...    0.727035
149835  Ordered something that never showed. Emailed t...    0.726005
92563   Thanks for messing up my order just because I ...    0.725914
35      my order hasn’t arrived (it was due 14th Octob...    0.724240
161722  hi my order is showing as delivered but it isn...    0.721112
3870    The item is being returned undelivered by the ...    0.712112
57863   Order:408-4742078-0005944 I HAVE NOT RECEIVED ...    0.711598
47721   Lies, I ordered this product and did not recei...    0.709786
22351   this is regarding my order# 171-5331733-110030...    0.707863
2767    I have an order that says delivered yesterday ...    0.705470
96154   My order from just was delivered. Opened it an...    0.705103
121128  Check out order number 701-4591572-1714631 I o...    0.704451
1772    I've received a message on one of my orders th...    0.701225
4417    item not received for order 406-1844716-623075...    0.700677
79260   OrderNo 171-4833625-7391554 isn't delivered it...    0.699857
37629   order number 111-0914388-7983449 canceled one ...    0.698864
38945   Ordered from and I get a delivery of an empty ...    0.698105
36991   Not received my product. But status is showing...    0.697902
16339   Since last September I have paid you for my or...    0.695858
123478  My order number is 408-9271797-1781967. The wr...    0.695453
37636   half of my order is still missing. i paid for ...    0.692425
92800   On that link on order was found ... I returned...    0.692376
156791  Yes. All but one of the items on my order arri...    0.692210
138892  my order keeps saying my order payment is a pr...    0.691417
25110   Yeah but it doesn't show the order I want to r...    0.689762
115599  I didn't get my order # 405-5128630-9070718 bu...    0.688577
28826   ORDER # 206-2798219-1329933 money taken no pro...    0.688283
37163   I have an order with two day delivery paid opt...    0.687414
67885                        my order did not reached yet    0.687058
42561                                Order did not arrive    0.686978
163238  Yeah it said last night my order was going to ...    0.686164
127354  My recent orders aren't displaying in My Accou...    0.685282
85916   , have ordered below items 10 days back and ha...    0.684212
16814   Help ! Ordered product and there's a part miss...    0.682491
89325                        The order has not arrived...    0.680990
80457   No papers or gift receipt. But once I dug thro...    0.680834
76665   can you cancel my order and refund money.The d...    0.680724
131569  Ya’ll not shipping my order and have been push...    0.679563

In [10]:
pd.set_option("display.max_colwidth", None)

delivery_delay_candidates = intent_candidates["DELIVERY_DELAY"][
    ["customer_text_clean", "similarity"]
].head(40)

display(delivery_delay_candidates)

,customer_text_clean,similarity
25731,"hello, My package was out for delivery but now it is saying it is delayed because courier was unable to arrange delivery",0.824175
34460,"Thankyou. Turns out delivery is late, should be due 1-4 Dec. Disappointing",0.776511
97154,Delivery date pending,0.774415
91358,Hi My package has missed two delivery dates but is now refundable if late by a further 10 months? Also Aug 10th isn't a Saturday?,0.755127
102504,"Delivery date is already delayed. 111-2691482-1933821 , also it says that it is a customer initiated delay which isn't right.",0.747700
18142,can you update me on my delivery that was already delayed and now even later than you said?,0.747494
90432,my package that was to arrive today still says out for delivery-it’s 930pm. Is it coming tonight? Need it for tomorrow.,0.740526
97237,Another expected delivery today and another delay courtesy of AMZL US!,0.739923
31049,"ich warte seit dem 4.10 auf eine Lieferung. Am 8.10 wurde sie durch einen Mitarbeiter verschoben, wann bekomme ich mein Paket?",0.724916
68726,No and no;the estimated delivery date is useless because only going to be in the us a few hours. The package was “guaranteed” for yesterday,0.721474
20429,I wish to complain about the late delivery of my package. Why is there not an email on your website to contact you about this?,0.721299
95885,"my package went from 2 day delivery to 6 day cus of a ""delay."" Twice Ive used prime shipping and haven't gotten things on time 😒",0.719322
113848,another one of our packages is late. This time by 4 days and it was a 2 day shipping order.,0.718141
38449,Two delayed packages from this week and their customer support is a joke. One of the packages is needed to be delivered today for an early Christmas gift for this Sunday.,0.714713
159067,I ordered a package on Friday to be delivered today and it’s not here. Now it’s not projected to be here til Wednesday or Thursday,0.712038
130233,"I need some information regarding a package I'm awaiting delivery for. Online it says it's final delivery attempt was yesterday, but I've had no email confirmation of this and I really need it delivered today!! Please help!",0.708570
78762,You missed by lot. Today's the delivery date. Package hasn't shown any movement in ~36 hrs.,0.706747
158309,The only thing was to figure out where the package is and try to delay it. Rep I’m chatting with now says they can guarantee a delayed delivery with USPS for Thursday. Is that true? Never heard of that before.,0.706396
57553,I have not received my package which was to be delivered yesterday.,0.704388
113791,I have not been given any new information on when my packages will arrive and they were due 3 days ago. Please help me,0.697671
38487,"Crappy delivery experience today. Took a half day off of work for my scheduled, enhanced delivery and it still hasn't arrived and no one can tell me when it will. Can you help?",0.693343
165874,"I've had two packages that were ""delayed"" in the past month. I live 30 minutes from your warehouse, can I just come pick it up? #21stcenturyproblems",0.689608
35843,"Yep, I’ve definitely noticed more delayed packages in the last few months. Had one today that was supposed to arrive but didn’t.",0.685160
41495,"Nouvelle date de livraison estimée : 2 déc. - 6 déc. Nous sommes désolés que votre colis soit en retard. Si vous ne l’avez pas reçu d’ici le jeudi 7 décembre, veuillez revenir sur cette page pour voir les options qui s'offrent à vous.",0.683919
145915,"Le suivi dit qu'une date de livraison est en attente, que je recevrais un mail pour m'informer de la livraison.",0.683171
149917,"It was due on Thursday. Has said ""out for delivery"" several timrs for a few days.",0.682709
10140,no! Don’t say my package is out for delivery and not deliver! Waited till 8pm then told 9pm then 10pm then still no parcel! 😤,0.682651
103259,Package says being delivered today by 8 PM that it's out for delivery. 8:19 and nothing USPS delivery says Monday. Why?,0.682397
201,The last update was on 22nd Oct saying it’s out for delivery.....you can’t tell me it take a over two weeks to deliver,0.681436
165250,I ordered something today that had 3-5 delivery days but then my email says there's no delivery date available .. can u help?,0.681322
118286,"I was supposed to receive my package by 8:00 pm today. It was last seen in Maryland this morning, after that there is no news about my package. WTF is going on? This is really very frustrating",0.680807
77165,"Please, where's my order? Delivery was at 8pm yrstdy, got a text at 7:47p informing me of undelivered package #URGENT",0.680649
19634,Someday the will deliver my package and the 2-day shipping thing will make sense. But it has been a week. #makethisright,0.680370
21954,no one come to home for delivering the package how can they update this status. I choose fast delivery option but they failed.,0.677863
104477,"Now expected 5 Nov - 8 Nov We're sorry your package is late. We're working to get your package back on track. Was expected Saturday, 4 Nov",0.675555
95880,"Delivery from 31 Oct - 2 Nov, item on the way. Hope it’s not US time on 2nd Nov",0.674428
21113,"The carrier is AMZL US. Unless the delivery arrives within the next 15 minutes, it's not likely my package will be delivered today.",0.673937
39741,"I have an order with the expected delivery date of Thursday, November 30th. It did not come. I have contacted live chat and they told me that it would come Friday, December 1st. It did not come as well. Now I'm being told to wait until December 2nd? Not helpful.",0.672461
128484,I'm supposed to get a package today but it is sitting at the post office (where it will sit for 36 hours before it's delivered) but this is the 2nd time in a week I've had an issue.,0.668161
118076,another package delayed. This is the 4th time in the past couple of months. What’s going on??!,0.667185

In [11]:
for idx, row in delivery_delay_candidates.iterrows():
    print(f"\n[{idx}] similarity={row['similarity']:.3f}")
    print(row["customer_text_clean"])

[25731] similarity=0.824
hello, My package was out for delivery but now it is saying it is delayed because courier was unable to arrange delivery

[34460] similarity=0.777
Thankyou. Turns out delivery is late, should be due 1-4 Dec. Disappointing

[97154] similarity=0.774
Delivery date pending

[91358] similarity=0.755
Hi My package has missed two delivery dates but is now refundable if late by a further 10 months? Also Aug 10th isn't a Saturday?

[102504] similarity=0.748
Delivery date is already delayed. 111-2691482-1933821 , also it says that it is a customer initiated delay which isn't right.

[18142] similarity=0.747
can you update me on my delivery that was already delayed and now even later than you said?

[90432] similarity=0.741
my package that was to arrive today still says out for delivery-it’s 930pm. Is it coming tonight? Need it for tomorrow.

[97237] similarity=0.740
Another expected delivery today and another delay courtesy of AMZL US!

[31049] similarity=0.725
ich warte seit dem 4.10 auf eine Lieferung. Am 8.10 wurde sie durch einen Mitarbeiter verschoben, wann bekomme ich mein Paket?

[68726] similarity=0.721
No and no;the estimated delivery date is useless because only going to be in the us a few hours. The package was “guaranteed” for yesterday

[20429] similarity=0.721
I wish to complain about the late delivery of my package. Why is there not an email on your website to contact you about this?

[95885] similarity=0.719
my package went from 2 day delivery to 6 day cus of a "delay." Twice Ive used prime shipping and haven't gotten things on time 😒

[113848] similarity=0.718
another one of our packages is late. This time by 4 days and it was a 2 day shipping order.

[38449] similarity=0.715
Two delayed packages from this week and their customer support is a joke. One of the packages is needed to be delivered today for an early Christmas gift for this Sunday.

[159067] similarity=0.712
I ordered a package on Friday to be delivered today and it’s not here. Now it’s not projected to be here til Wednesday or Thursday

[130233] similarity=0.709
I need some information regarding a package I'm awaiting delivery for. Online it says it's final delivery attempt was yesterday, but I've had no email confirmation of this and I really need it delivered today!! Please help!

[78762] similarity=0.707
You missed by lot. Today's the delivery date. Package hasn't shown any movement in ~36 hrs.

[158309] similarity=0.706
The only thing was to figure out where the package is and try to delay it. Rep I’m chatting with now says they can guarantee a delayed delivery with USPS for Thursday. Is that true? Never heard of that before.

[57553] similarity=0.704
I have not received my package which was to be delivered yesterday.

[113791] similarity=0.698
I have not been given any new information on when my packages will arrive and they were due 3 days ago. Please help me

[38487] similarity=0.693
Crappy delivery experience today. Took a half day off of work for my scheduled, enhanced delivery and it still hasn't arrived and no one can tell me when it will. Can you help?

[165874] similarity=0.690
I've had two packages that were "delayed" in the past month. I live 30 minutes from your warehouse, can I just come pick it up? #21stcenturyproblems

[35843] similarity=0.685
Yep, I’ve definitely noticed more delayed packages in the last few months. Had one today that was supposed to arrive but didn’t.

[41495] similarity=0.684
Nouvelle date de livraison estimée : 2 déc. - 6 déc. Nous sommes désolés que votre colis soit en retard. Si vous ne l’avez pas reçu d’ici le jeudi 7 décembre, veuillez revenir sur cette page pour voir les options qui s'offrent à vous.

[145915] similarity=0.683
Le suivi dit qu'une date de livraison est en attente, que je recevrais un mail pour m'informer de la livraison.

[149917] similarity=0.683
It was due on Thursday. Has said "out for delivery" several timrs for a few days.

[10140] similarity=0.683
no! Don’t say my package is out for delivery and not deliver! Waited till 8pm then told 9pm then 10pm then still no parcel! 😤

[103259] similarity=0.682
Package says being delivered today by 8 PM that it's out for delivery. 8:19 and nothing USPS delivery says Monday. Why?

[201] similarity=0.681
The last update was on 22nd Oct saying it’s out for delivery.....you can’t tell me it take a over two weeks to deliver

[165250] similarity=0.681
I ordered something today that had 3-5 delivery days but then my email says there's no delivery date available .. can u help?

[118286] similarity=0.681
I was supposed to receive my package by 8:00 pm today. It was last seen in Maryland this morning, after that there is no news about my package. WTF is going on? This is really very frustrating

[77165] similarity=0.681
Please, where's my order? Delivery was at 8pm yrstdy, got a text at 7:47p informing me of undelivered package #URGENT

[19634] similarity=0.680
Someday the will deliver my package and the 2-day shipping thing will make sense. But it has been a week. #makethisright

[21954] similarity=0.678
no one come to home for delivering the package how can they update this status. I choose fast delivery option but they failed.

[104477] similarity=0.676
Now expected 5 Nov - 8 Nov We're sorry your package is late. We're working to get your package back on track. Was expected Saturday, 4 Nov

[95880] similarity=0.674
Delivery from 31 Oct - 2 Nov, item on the way. Hope it’s not US time on 2nd Nov

[21113] similarity=0.674
The carrier is AMZL US. Unless the delivery arrives within the next 15 minutes, it's not likely my package will be delivered today.

[39741] similarity=0.672
I have an order with the expected delivery date of Thursday, November 30th. It did not come. I have contacted live chat and they told me that it would come Friday, December 1st. It did not come as well. Now I'm being told to wait until December 2nd? Not helpful.

[128484] similarity=0.668
I'm supposed to get a package today but it is sitting at the post office (where it will sit for 36 hours before it's delivered) but this is the 2nd time in a week I've had an issue.

[118076] similarity=0.667
another package delayed. This is the 4th time in the past couple of months. What’s going on??!

In [12]:
golden_candidates = []

for intent, candidates in intent_candidates.items():
    temp = candidates.copy()

    temp["candidate_intent"] = intent
    temp["human_intent"] = ""
    temp["difficulty"] = ""
    temp["notes"] = ""

    golden_candidates.append(temp)

golden_candidates = pd.concat(
    golden_candidates,
    ignore_index=True
)

golden_candidates = golden_candidates[
    [
        "customer_tweet_id",
        "customer_text",
        "customer_text_clean",
        "candidate_intent",
        "similarity",
        "human_intent",
        "difficulty",
        "notes"
    ]
]

golden_candidates.head()

,customer_tweet_id,customer_text,customer_text_clean,candidate_intent,similarity,human_intent,difficulty,notes
0,351833,"@AmazonHelp hello, My package was out for delivery but now it is saying it is delayed because courier was unable to arrange delivery","hello, My package was out for delivery but now it is saying it is delayed because courier was unable to arrange delivery",DELIVERY_DELAY,0.824175,,,
1,448256,"@AmazonHelp Thankyou. Turns out delivery is late, should be due 1-4 Dec. Disappointing","Thankyou. Turns out delivery is late, should be due 1-4 Dec. Disappointing",DELIVERY_DELAY,0.776511,,,
2,1484058,Delivery date pending https://t.co/eFKBoj7LA7,Delivery date pending,DELIVERY_DELAY,0.774415,,,
3,1385298,Hi @115830\nMy package has missed two delivery dates but is now refundable if late by a further 10 months? Also Aug 10th isn't a Saturday? https://t.co/YGr1AdoFt3,Hi My package has missed two delivery dates but is now refundable if late by a further 10 months? Also Aug 10th isn't a Saturday?,DELIVERY_DELAY,0.755127,,,
4,1575619,"@AmazonHelp Delivery date is already delayed. 111-2691482-1933821 , also it says that it is a customer initiated delay which isn't right.","Delivery date is already delayed. 111-2691482-1933821 , also it says that it is a customer initiated delay which isn't right.",DELIVERY_DELAY,0.747700,,,

### Start building candidate pool

In [13]:
# Take the top 25 semantic candidates for every intent
candidate_parts = []

for intent, candidates in intent_candidates.items():
    temp = candidates.head(25).copy()
    temp["candidate_intent"] = intent
    candidate_parts.append(temp)

semantic_pool = pd.concat(candidate_parts, ignore_index=True)

print("Before deduplication:", len(semantic_pool))
print("Unique tweets:", semantic_pool["customer_tweet_id"].nunique())

Before deduplication: 375
Unique tweets: 338

In [14]:
semantic_pool = (
    semantic_pool
    .sort_values("similarity", ascending=False)
    .drop_duplicates("customer_tweet_id")
    .reset_index(drop=True)
)

print("After deduplication:", len(semantic_pool))

After deduplication: 338

In [15]:
random_pool = amazon_pairs.sample(
    n=100,
    random_state=123
).copy()

random_pool["candidate_intent"] = "RANDOM"
random_pool["similarity"] = np.nan

In [16]:
random_pool = random_pool[
    [
        "customer_tweet_id",
        "customer_text",
        "customer_text_clean",
        "candidate_intent",
        "similarity"
    ]
]

In [17]:
semantic_pool = semantic_pool[
    [
        "customer_tweet_id",
        "customer_text",
        "customer_text_clean",
        "candidate_intent",
        "similarity"
    ]
]

candidate_pool = pd.concat(
    [semantic_pool, random_pool],
    ignore_index=True
)

candidate_pool = (
    candidate_pool
    .drop_duplicates("customer_tweet_id")
    .sample(frac=1, random_state=42)
    .reset_index(drop=True)
)

print("Final candidate pool:", len(candidate_pool))

Final candidate pool: 438

In [18]:
candidate_pool["human_intent"] = ""
candidate_pool["difficulty"] = ""
candidate_pool["notes"] = ""

In [19]:
display(
    candidate_pool[
        [
            "customer_tweet_id",
            "customer_text",
            "candidate_intent",
            "similarity",
            "human_intent",
            "difficulty",
            "notes"
        ]
    ].head(30)
)

,customer_tweet_id,customer_text,candidate_intent,similarity,human_intent,difficulty,notes
0,2797118,@AmazonHelp Hola! Son vendidos directamente por Amazon.,RANDOM,NaN,,,
1,1222599,@115821 seriously disappointed in your lack of security. My account was hacked and nobody is in a hurry to help me :(,ACCOUNT_SECURITY,0.739902,,,
2,376282,@AmazonHelp I was ordered 2 no’s above item but I received only one short buy yesterday https://t.co/AmZ1uxwd0I,WRONG_ITEM_RECEIVED,0.576438,,,
3,1087661,@AmazonHelp https://t.co/8aZ3NUAScP. 🤘🤘,RANDOM,NaN,,,
4,2972777,今更ながらアマゾンビデオで動画ダウンロードしておけば外でも通信量なしで観れるの気づいたので、昼休みとか利用してアニメ観よう。まずはメイドインアビス,RANDOM,NaN,,,
5,233785,@AmazonHelp Tracking on Canada Post says delivered on the 29th. Not updated on Amazon though.,DELIVERY_TRACKING,0.552647,,,
6,314242,@115850 Pathetic service! Its been 10 days to receive my order still cash back isn't received. No call connect in Customer Care,CASHBACK,0.655791,,,
7,2856569,"@AmazonHelp hola! Hice un pedido de dos artículos, uno en preventa y otro fuera de stock, he cancelado el del stock y creo que el de preventa también pero ese no quería cancelarlo. Me dice que se está preparando la cancelación pero quiero volvero a pedir, cuando podré?",ORDER_CANCELLATION,0.736567,,,
8,236254,@AmazonHelp V r talking abt Mumbai- r u saying dt largest e-commerce player can't deliver products in a metro city like Mumbai? Contd..,RANDOM,NaN,,,
9,250577,"shiiiiit I love how amazon is like, “the delivery driver is 5 minutes away from your house” \n\nthey’re most consistent than the girls I’ve talked to",RANDOM,NaN,,,
10,2929564,@115850 where is my order? Tracking details not updated for last 12 hrs guaranteed to be delivered today\n@AmazonHelp,DELIVERY_TRACKING,0.551257,,,
11,1375327,@AmazonHelp my package that was to arrive today still says out for delivery-it’s 930pm. Is it coming tonight? Need it for tomorrow.,DELIVERY_DELAY,0.740526,,,
12,1770527,@AmazonHelp I can't chat because I can't login to my account. Please send me the phone number to call.,ACCOUNT_ACCESS,0.652471,,,
13,2609978,Shameful waste of packaging @115830 - an image of my Brother receiving a mop! Excessive &amp; wasteful. Clean up your act! #LessWaste https://t.co/I6F75CjXTe,RANDOM,NaN,,,
14,2211987,"@115850 My order number is 408-9271797-1781967. The wrong item was delivered TWICE against this order number. Its been about 2 weeks or so since the item was returned (the second time). Please update immediately when the refund (Rs. 1765) would be made, thanks",MISSING_ITEM,0.695453,,,
15,1151151,@AmazonHelp Could you please explain me the procedure to cancel the order...I don't want any more false promises n bullshit ...,ORDER_CANCELLATION,0.740027,,,
16,2868397,@132976 Wow. Die Synchronisation ist unterirdisch. Warum nicht einfach Untertitel?,RANDOM,NaN,,,
17,361352,"@AmazonHelp View order details\nOrder date\n09-Sep-2017\nOrder #\n405-7676708-3857148\nOrder total\n 3,635.00 (1 item)",ORDER_STATUS,0.675178,,,
18,120243,@AmazonHelp “Return started\nYour refund will be processed”. I confirmed with customer service it arrived last Tuesday 11/14,REFUND_STATUS,0.741043,,,
19,250024,@AmazonHelp Since last September I have paid you for my order .item could not delivered but did not returned my money,MISSING_ITEM,0.695858,,,
20,931834,@AmazonHelp I think I was charged twice it only should have been once. https://t.co/HkLJVw1iRn,UNEXPECTED_CHARGE,0.842482,,,
21,966792,@AmazonHelp amazon said my package was supposed to come today but USPS website said its not even there yet,DELIVERY_NOT_RECEIVED,0.687424,,,
22,1206184,Hi @115830. I'd like to cancel an order which should have been delivered on Friday and still hasn't arrived. Please can you tell me how?,ORDER_CANCELLATION,0.790134,,,
23,2322141,@AmazonHelp Not getting reply even after sending 2 reminders on email,RANDOM,NaN,,,
24,2906612,@AmazonHelp hi my order is showing as delivered but it isn’t here? I’ve been home all day so couldn’t have missed it. Order number: 204-8120334-0987527,MISSING_ITEM,0.721112,,,
25,55059,@115830 @AmazonHelp I have an order that says delivered yesterday by amazon shipping but it hasn’t been delivered. What can I do?,MISSING_ITEM,0.705470,,,
26,1289735,@115821 Account corrected! I’ve called 3 times and gotten the run around! I can’t log in to my own account #pleasehelp @115821 #thisisridiculous,ACCOUNT_ACCESS,0.745170,,,
27,2891806,It would seem my local 3PL Amazon delivery man knows what Hannah’s getting for Christmas. Disgusting. https://t.co/o3i4Kjafso,RANDOM,NaN,,,
28,1529943,3 livraisons de commandes @120533 Prime non livrées par @120535 alors que j'étais présent toute la journée ! WTF ?! https://t.co/VTIKKIXsP7,RANDOM,NaN,,,
29,2531725,@115821 @115850 @AmazonHelp After a one month wait period and thrice changed delivery date your support asks me to cancel my order !!!,ORDER_CANCELLATION,0.755342,,,

In [20]:
golden_candidate_path = Path("../data/golden")

golden_candidate_path.mkdir(
    parents=True,
    exist_ok=True
)

candidate_pool.to_csv(
    golden_candidate_path / "golden_candidate_pool.csv",
    index=False
)

print("Saved:", golden_candidate_path / "golden_candidate_pool.csv")

Saved: ..\data\golden\golden_candidate_pool.csv

In [21]:
candidate_pool["candidate_intent"].value_counts()

candidate_intent
RANDOM                   100
ORDER_CANCELLATION        25
MISSING_ITEM              25
ORDER_STATUS              25
REFUND_STATUS             25
UNEXPECTED_CHARGE         25
DELIVERY_NOT_RECEIVED     25
DELIVERY_DELAY            24
CASHBACK                  23
ACCOUNT_ACCESS            22
DELIVERY_DRIVER_ISSUE     22
DELIVERY_TRACKING         21
PRODUCT_ISSUE             21
ACCOUNT_SECURITY          19
WRONG_ITEM_RECEIVED       18
RETURN_REPLACEMENT        18
Name: count, dtype: int64

In [22]:
candidate_pool["candidate_intent"].value_counts(normalize=True).round(3)

candidate_intent
RANDOM                   0.228
ORDER_CANCELLATION       0.057
MISSING_ITEM             0.057
ORDER_STATUS             0.057
REFUND_STATUS            0.057
UNEXPECTED_CHARGE        0.057
DELIVERY_NOT_RECEIVED    0.057
DELIVERY_DELAY           0.055
CASHBACK                 0.053
ACCOUNT_ACCESS           0.050
DELIVERY_DRIVER_ISSUE    0.050
DELIVERY_TRACKING        0.048
PRODUCT_ISSUE            0.048
ACCOUNT_SECURITY         0.043
WRONG_ITEM_RECEIVED      0.041
RETURN_REPLACEMENT       0.041
Name: proportion, dtype: float64

In [23]:
annotation_df = candidate_pool[
    [
        "customer_tweet_id",
        "customer_text",
        "candidate_intent",
        "similarity"
    ]
].copy()

annotation_df["human_intent"] = ""
annotation_df["difficulty"] = ""
annotation_df["notes"] = ""

annotation_df = annotation_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

annotation_path = Path("../data/golden/amazon_golden_annotation.csv")

annotation_df.to_csv(
    annotation_path,
    index=False
)

print("Saved:", annotation_path)
print("Rows:", len(annotation_df))

Saved: ..\data\golden\amazon_golden_annotation.csv
Rows: 438

In [46]:
batch_1 = annotation_df.iloc[150:199].copy()

display(
    batch_1[
        [
            "customer_tweet_id",
            "customer_text",
            "candidate_intent",
            "similarity",
            "human_intent",
            "difficulty",
            "notes"
        ]
    ]
)

,customer_tweet_id,customer_text,candidate_intent,similarity,human_intent,difficulty,notes
150,928315,I have spend 31k on a product and i get a defective one? @115850 @AmazonHelp &amp; no replacement for it? https://t.co/Rr1d7IHS8P,PRODUCT_ISSUE,0.687471,DELIVERY_NOT_RECEIVED,EASY,Product/package not received despite delivered status
151,1385298,Hi @115830\nMy package has missed two delivery dates but is now refundable if late by a further 10 months? Also Aug 10th isn't a Saturday? https://t.co/YGr1AdoFt3,DELIVERY_DELAY,0.755127,DELIVERY_TRACKING,EASY,Carrier tracking and Amazon status disagree
152,1048775,Another failed delivery from @117795 Getting fed up with this as have lost count of the number of deliveries that have failed,DELIVERY_DRIVER_ISSUE,0.611137,ACCOUNT_ACCESS,EASY,Cannot sign in; password rejected
153,1401461,@115821 so a package was supposed to be delivered today. Tracking last shows it left on Thursday but nothing since and package not at home any ideas?,DELIVERY_TRACKING,0.610237,ACCOUNT_SECURITY,EASY,Account compromise/fraud accusation
154,1283811,@AmazonHelp product delivered not up to the quality standard. Not expected this quality. Want to return! Please help,PRODUCT_ISSUE,0.523920,MISSING_ITEM,BOUNDARY,One item never arrived; refund is secondary
155,685683,"@115830 Now I can't get into my account at all, you're a bunch of thieving Ba****ds!",ACCOUNT_ACCESS,0.661874,REFUND_STATUS,EASY,Asking about refund initiation
156,1205000,@AmazonHelp Just get my package it was suppose to be here today but oh no,DELIVERY_NOT_RECEIVED,0.689905,OTHER,MESSY,Complaint without a clearly supported operational intent
157,1391145,"@AmazonHelp You have charged me twice to two items, my bank confirmed it, I gave the codes to you but still you're denying it. Unbelievable.",UNEXPECTED_CHARGE,0.576666,OTHER,MESSY,Synchronization/account feature issue outside taxonomy
158,2042074,@AmazonHelp Yes but the bank says you have double charged but you refuse to acknowledge that or talk to them. This has been happening frequently.,UNEXPECTED_CHARGE,0.546747,ORDER_CANCELLATION,EASY,Asking why order was cancelled
159,1595329,@AmazonHelp last month my card was charged for prume when even though its canceled and it did it again this month,UNEXPECTED_CHARGE,0.499057,DELIVERY_DELAY,EASY,Explicitly says delivery date is delayed
160,2847336,"Ordered a new sd card from @115830 and it charged me twice, great 😑",UNEXPECTED_CHARGE,0.536391,UNEXPECTED_CHARGE,BOUNDARY,Charge during presumed trial period
161,527631,@115850 received a broken item in my order. Asked for replacement 2dayd back. No progress yet. This isn't the way customers should be handled. #badshopping@amazon,PRODUCT_ISSUE,0.531313,OTHER,MESSY,No clear support request
162,1201193,"Ummmm as an @115821 prime member, I’m highly disappointed that my shipping time has been extended😒😒",RANDOM,NaN,REFUND_STATUS,EASY,Refund processing status
163,320381,"@AmazonHelp Yes I have reported, But what about my order which is supposed to be delivered on 6th Oct with #PRIME....#3DAYSDELAY",ORDER_STATUS,0.674119,ACCOUNT_ACCESS,BOUNDARY,Vague account trouble; access issue implied
164,467369,"@226254 @115821 Yep, I’ve definitely noticed more delayed packages in the last few months. Had one today that was supposed to arrive but didn’t.",DELIVERY_DELAY,0.685160,REFUND_STATUS,BOUNDARY,Refund promised but hasn't happened
165,422037,@115850 hey where is my refund??,REFUND_STATUS,0.848526,ORDER_STATUS,EASY,Asking about order history/status
166,2360459,"@AmazonHelp Really, whats the point of paying for prime when i cant gave my packages delivered on time?",RANDOM,NaN,OTHER,MESSY,Seller context without actionable supported intent
167,2142881,"@AmazonHelp Yes, I already checked, so Is there anyway I can get the money back and get acces to my account",CASHBACK,0.667502,RETURN_REPLACEMENT,EASY,Explicit return request
168,2688064,@AmazonHelp There’s no card thingy so don’t know who the carrier is... it’s not with a neighbour and not in my ‘safe place’... there wasn’t even a knock on the door to attempt to deliver it!,RANDOM,NaN,OTHER,MESSY,Manufacturer hasn't replied; insufficient context
169,1545998,@AmazonHelp I've sent the details. Please just cancel the order. It's not worth all the hassle and waste of time I'm going through for it.,ORDER_CANCELLATION,0.767231,DELIVERY_TRACKING,EASY,Tracking details
170,385364,@AmazonHelp what is the point in having delivery instructions if your drivers ignores them?,DELIVERY_DRIVER_ISSUE,0.645573,OTHER,MESSY,Generic follow-up with insufficient context
171,128829,@AmazonHelp @115850 Played every quiz but still till date not a single winner name came out. Transparency is not there. You should publish name on your Twitter account @AmazonHelp @115850 if its not just a publicity stunt and advertising idea,RANDOM,NaN,ORDER_CANCELLATION,BOUNDARY,Customer is being asked to cancel after delivery-date changes
172,2855134,"uh amazon charged me twice for the same item, what d0",UNEXPECTED_CHARGE,0.540196,PRODUCT_ISSUE,BOUNDARY,Product problem; resolution delay is secondary
173,2460018,@115850 Not credited 99 cashback for Jio 459 recharge,CASHBACK,0.654995,ORDER_STATUS,EASY,Explicitly asks order status
174,56932,@115850 How can refunds this my money https://t.co/vzd9YnpQ6U,REFUND_STATUS,0.862839,REFUND_STATUS,EASY,Refund amount doesn't match purchase price
175,2216878,@AmazonHelp Was eligible for a cashback under SbI cashback offer back in August. Didn't receive yet,CASHBACK,0.729333,ACCOUNT_ACCESS,EASY,Cannot log into account
176,80798,@115850 item not received for order 406-1844716-6230753 Status is showing delivered . Have also received SMS mentioning item delivered. Kindly address urgently.,MISSING_ITEM,0.700677,ORDER_CANCELLATION,EASY,Order cancellation issue
177,314242,@115850 Pathetic service! Its been 10 days to receive my order still cash back isn't received. No call connect in Customer Care,CASHBACK,0.655791,PRODUCT_ISSUE,EASY,Defective product; exchange requested
178,1695,@115821 my order hasn’t arrived (it was due 14th October). Can you help?,MISSING_ITEM,0.724240,ACCOUNT_SECURITY,EASY,Attempted account compromise
179,1041740,Hey @115821 thanks for locking my account. Now I can't login to get customer service to unlock my account. #fail,ACCOUNT_ACCESS,0.774333,OTHER,MESSY,Invoice-copy request outside taxonomy
180,290429,"@115821 is awesome. They made sure I got my order on time, despite saying it would be delayed. Maybe awesome customer service is the real reason they are killing retail.",RANDOM,NaN,ORDER_STATUS,EASY,Asking to check order details
181,2662261,@AmazonHelp I was Queen of Hearts for the weekend. And I'll be a mermaid for Halloween night 😉,RANDOM,NaN,ACCOUNT_ACCESS,EASY,Unable to log in
182,985034,@AmazonHelp My refund is still not done,REFUND_STATUS,0.856587,CASHBACK,EASY,Cashback not received
183,2929564,@115850 where is my order? Tracking details not updated for last 12 hrs guaranteed to be delivered today\n@AmazonHelp,DELIVERY_TRACKING,0.551257,ORDER_CANCELLATION,EASY,Explicit cancellation
184,2940219,@AmazonHelp hi. I have ordered an item with was split into 2 deliveries. I seem to have been charged once for the full cost of the item and then a second charge for the second part of the delivery.,UNEXPECTED_CHARGE,0.478007,PRODUCT_ISSUE,BOUNDARY,Broken product; replacement secondary
185,512452,Ordered from @115821 and I get a delivery of an empty box. #Frustrated,MISSING_ITEM,0.698105,PRODUCT_ISSUE,EASY,Replaced product still doesn't work
186,39558,"I got my refund from @115821 for my copy of odyssey, but was hit with a restocking fee because their delivery people can't do their job.",REFUND_STATUS,0.712684,OTHER,MESSY,No actionable intent
187,1216274,I was supposed to get a package almost a month ago &amp; it still has not showed. Help! @115821 @134682 @AmazonHelp @81,DELIVERY_NOT_RECEIVED,0.778103,DELIVERY_TRACKING,EASY,Explicit tracking number/status
188,2319449,"@AmazonHelp I need some information regarding a package I'm awaiting delivery for. Online it says it's final delivery attempt was yesterday, but I've had no email confirmation of this and I really need it delivered today!! Please help!",DELIVERY_DELAY,0.708570,RETURN_REPLACEMENT,BOUNDARY,Returned item/order; return context primary
189,56859,.@115821 why is my account being hacked like every week now...! https://t.co/zToW3sG9CC,ACCOUNT_SECURITY,0.783339,UNEXPECTED_CHARGE,EASY,Explicit duplicate charge
190,503442,"@115821 Crappy delivery experience today. Took a half day off of work for my scheduled, enhanced delivery and it still hasn't arrived and no one can tell me when it will. Can you help?",DELIVERY_DELAY,0.693343,OTHER,MESSY,Generic thanks
191,1435688,"@AmazonHelp Bonjour, il s’agit d’un retour que je compte faire, pour un produit en cours de livraison.",RANDOM,NaN,ORDER_CANCELLATION,EASY,Order cancelled unexpectedly
192,1093244,@115850 help me wrong product collected for return,WRONG_ITEM_RECEIVED,0.599304,PRODUCT_ISSUE,EASY,Product arrived damaged
193,790186,@AmazonHelp @115851 thanks a lot to you. I have received the product now which is defective..,PRODUCT_ISSUE,0.666483,DELIVERY_NOT_RECEIVED,BOUNDARY,Customer says product hasn't been received
194,2974887,@115821 #help I had a package delivered today and my item was broken what do I do?,WRONG_ITEM_RECEIVED,0.604592,ACCOUNT_SECURITY,EASY,Bank details stolen/used with account
195,255735,"@AmazonHelp just got an email that you guys changed an email for one of my accounts, which I didn’t put the request in for Someone hacked it",ACCOUNT_SECURITY,0.662529,DELIVERY_NOT_RECEIVED,EASY,Delivered but not received
196,2394957,@AmazonHelp リプライありがとうございます！\n普段代引きしかしたことが無かったので。\nAmazonギフト券を使い購入すればいいのですね！分かりました。ありがとうございます！,RANDOM,NaN,OTHER,MESSY,Simple acknowledgement
197,456530,"@AmazonHelp You messed up a delivery, offered free items as compensation then messed up that delivery and when I complained you withdrew the original compensatory offer",WRONG_ITEM_RECEIVED,0.579657,ACCOUNT_ACCESS,EASY,Login/password-reset problem
198,1127124,@AmazonHelp There is no point since no update is given to me regarding product. If it's damaged please let me know. I'm already emailing since few days https://t.co/fweFvcuUFX,PRODUCT_ISSUE,0.673734,DELIVERY_DELAY,EASY,Expected delivery date has passed

### Out-of-taxonomy rule

If a message does not clearly correspond to any supported operational intent,
label it `OTHER` rather than forcing it into the closest intent.

`OTHER` is an evaluation/rejection class, not one of the 15 business intents.

Examples:
- praise or compliments
- generic comments without a support request
- unsupported Prime/membership questions
- messages too ambiguous to map reliably

### Primary-intent rule

When a message contains multiple issues, label the intent corresponding to
the customer's primary operational problem.

Examples:

"Tracking says delivered but I never received the package."
→ DELIVERY_NOT_RECEIVED

"My package was supposed to arrive yesterday but tracking hasn't updated."
→ DELIVERY_DELAY

"How do I track the package that I returned?"
→ RETURN_REPLACEMENT

In [47]:
print("Total candidates:", len(annotation_df))
print("Annotated:", annotation_df["human_intent"].ne("").sum())
print("Unannotated:", annotation_df["human_intent"].eq("").sum())

Total candidates: 438
Annotated: 197
Unannotated: 241

In [44]:
for i, (intent, difficulty, note) in enumerate(labels_100_148,start=150):
    annotation_df.loc[i, "human_intent"] = intent
    annotation_df.loc[i, "difficulty"] = difficulty
    annotation_df.loc[i, "notes"] = note

In [48]:
golden_df = annotation_df[
    annotation_df["human_intent"].ne("")
].copy()

print(
    golden_df["human_intent"]
    .value_counts()
)

human_intent
OTHER                    37
ORDER_CANCELLATION       19
REFUND_STATUS            17
DELIVERY_NOT_RECEIVED    16
DELIVERY_TRACKING        16
ACCOUNT_ACCESS           15
PRODUCT_ISSUE            13
ACCOUNT_SECURITY         12
ORDER_STATUS             12
DELIVERY_DELAY           11
RETURN_REPLACEMENT        9
UNEXPECTED_CHARGE         9
CASHBACK                  5
MISSING_ITEM              3
DELIVERY_DRIVER_ISSUE     3
Name: count, dtype: int64

In [49]:
print(
    golden_df["difficulty"]
    .value_counts()
)

difficulty
EASY        123
MESSY        40
BOUNDARY     34
Name: count, dtype: int64

In [50]:
pd.crosstab(
    golden_df["human_intent"],
    golden_df["difficulty"]
)

difficulty             BOUNDARY  EASY  MESSY
human_intent
ACCOUNT_ACCESS                2    13      0
ACCOUNT_SECURITY              0    11      1
CASHBACK                      0     5      0
DELIVERY_DELAY                3     6      2
DELIVERY_DRIVER_ISSUE         0     3      0
DELIVERY_NOT_RECEIVED         4    12      0
DELIVERY_TRACKING             3    13      0
MISSING_ITEM                  2     1      0
ORDER_CANCELLATION            2    17      0
ORDER_STATUS                  1    11      0
OTHER                         0     0     37
PRODUCT_ISSUE                 5     8      0
REFUND_STATUS                 5    12      0
RETURN_REPLACEMENT            4     5      0
UNEXPECTED_CHARGE             3     6      0

In [53]:
print(
    "Duplicate tweet IDs:",
    golden_df["customer_tweet_id"].duplicated().sum()
)

print(
    "Duplicate texts:",
    golden_df["customer_text"].duplicated().sum()
)

Duplicate tweet IDs: 0
Duplicate texts: 0

In [55]:
golden_columns = [
    "customer_tweet_id",
    "customer_text",
    "customer_text",
    "human_intent",
    "difficulty",
    "notes"
]

golden_df = golden_df[golden_columns].copy()

golden_path = Path("../data/golden/amazon_golden_set.csv")

golden_df.to_csv(
    golden_path,
    index=False
)

print(f"Saved {len(golden_df)} examples to:")
print(golden_path)

Saved 197 examples to:
..\data\golden\amazon_golden_set.csv

In [56]:
golden_df["human_intent"].value_counts()

human_intent
OTHER                    37
ORDER_CANCELLATION       19
REFUND_STATUS            17
DELIVERY_NOT_RECEIVED    16
DELIVERY_TRACKING        16
ACCOUNT_ACCESS           15
PRODUCT_ISSUE            13
ACCOUNT_SECURITY         12
ORDER_STATUS             12
DELIVERY_DELAY           11
RETURN_REPLACEMENT        9
UNEXPECTED_CHARGE         9
CASHBACK                  5
MISSING_ITEM              3
DELIVERY_DRIVER_ISSUE     3
Name: count, dtype: int64

In [57]:
pd.crosstab(
    golden_df["human_intent"],
    golden_df["difficulty"]
)

difficulty             BOUNDARY  EASY  MESSY
human_intent
ACCOUNT_ACCESS                2    13      0
ACCOUNT_SECURITY              0    11      1
CASHBACK                      0     5      0
DELIVERY_DELAY                3     6      2
DELIVERY_DRIVER_ISSUE         0     3      0
DELIVERY_NOT_RECEIVED         4    12      0
DELIVERY_TRACKING             3    13      0
MISSING_ITEM                  2     1      0
ORDER_CANCELLATION            2    17      0
ORDER_STATUS                  1    11      0
OTHER                         0     0     37
PRODUCT_ISSUE                 5     8      0
REFUND_STATUS                 5    12      0
RETURN_REPLACEMENT            4     5      0
UNEXPECTED_CHARGE             3     6      0

In [58]:
golden_df["human_intent"].value_counts().sort_index()

human_intent
ACCOUNT_ACCESS           15
ACCOUNT_SECURITY         12
CASHBACK                  5
DELIVERY_DELAY           11
DELIVERY_DRIVER_ISSUE     3
DELIVERY_NOT_RECEIVED    16
DELIVERY_TRACKING        16
MISSING_ITEM              3
ORDER_CANCELLATION       19
ORDER_STATUS             12
OTHER                    37
PRODUCT_ISSUE            13
REFUND_STATUS            17
RETURN_REPLACEMENT        9
UNEXPECTED_CHARGE         9
Name: count, dtype: int64

In [59]:
remaining = annotation_df[
    annotation_df["human_intent"].eq("")
].copy()

print("Remaining:", len(remaining))

Remaining: 241

In [60]:
rare_candidates = remaining[
    remaining["candidate_intent"].isin([
        "MISSING_ITEM",
        "DELIVERY_DRIVER_ISSUE",
        "CASHBACK",
        "WRONG_ITEM_RECEIVED",
        "RETURN_REPLACEMENT"
    ])
].copy()

print(
    rare_candidates["candidate_intent"]
    .value_counts()
)

candidate_intent
DELIVERY_DRIVER_ISSUE    19
WRONG_ITEM_RECEIVED      14
RETURN_REPLACEMENT       13
MISSING_ITEM             11
CASHBACK                 11
Name: count, dtype: int64

In [63]:
# Add selected rare-intent examples
labels_to_add = {
    201: "MISSING_ITEM",
    381: "MISSING_ITEM",
    426: "MISSING_ITEM",

    222: "DELIVERY_DRIVER_ISSUE",
    244: "DELIVERY_DRIVER_ISSUE",
    262: "DELIVERY_DRIVER_ISSUE",
    312: "DELIVERY_DRIVER_ISSUE",
    361: "DELIVERY_DRIVER_ISSUE",

    205: "CASHBACK",
    255: "CASHBACK",
    334: "CASHBACK",

    254: "WRONG_ITEM_RECEIVED",
    340: "WRONG_ITEM_RECEIVED",
    372: "WRONG_ITEM_RECEIVED",
    377: "WRONG_ITEM_RECEIVED",
    431: "WRONG_ITEM_RECEIVED",
}

for idx, label in labels_to_add.items():
    annotation_df.loc[idx, "human_intent"] = label

In [64]:
golden_df = annotation_df[
    annotation_df["human_intent"].notna() &
    (annotation_df["human_intent"] != "")
].copy()

print("Golden set size:", len(golden_df))
print()
print(golden_df["human_intent"].value_counts())

Golden set size: 213

human_intent
OTHER                    37
ORDER_CANCELLATION       19
REFUND_STATUS            17
DELIVERY_NOT_RECEIVED    16
DELIVERY_TRACKING        16
ACCOUNT_ACCESS           15
PRODUCT_ISSUE            13
ACCOUNT_SECURITY         12
ORDER_STATUS             12
DELIVERY_DELAY           11
RETURN_REPLACEMENT        9
UNEXPECTED_CHARGE         9
CASHBACK                  8
DELIVERY_DRIVER_ISSUE     8
MISSING_ITEM              6
WRONG_ITEM_RECEIVED       5
Name: count, dtype: int64

In [66]:
golden_df = annotation_df[
    annotation_df["human_intent"].notna() &
    (annotation_df["human_intent"] != "")
].copy()

golden_columns = [
    "customer_tweet_id",
    "customer_text",
    "customer_text",
    "human_intent",
    "difficulty",
    "notes"
]

golden_df = golden_df[golden_columns].copy()

golden_path = Path("../data/golden/amazon_golden_set.csv")

golden_df.to_csv(
    golden_path,
    index=False
)

print(f"Saved {len(golden_df)} examples")
print(golden_path)

Saved 213 examples
..\data\golden\amazon_golden_set.csv

In [68]:
print("Size:", len(golden_df))
print("Duplicate IDs:", golden_df["customer_tweet_id"].duplicated().sum())
print("Duplicate texts:", golden_df["customer_text"].duplicated().sum())

print("\nIntent distribution:")
print(golden_df["human_intent"].value_counts())

Size: 213
Duplicate IDs: 0
Duplicate texts: 0

Intent distribution:
human_intent
OTHER                    37
ORDER_CANCELLATION       19
REFUND_STATUS            17
DELIVERY_NOT_RECEIVED    16
DELIVERY_TRACKING        16
ACCOUNT_ACCESS           15
PRODUCT_ISSUE            13
ACCOUNT_SECURITY         12
ORDER_STATUS             12
DELIVERY_DELAY           11
RETURN_REPLACEMENT        9
UNEXPECTED_CHARGE         9
CASHBACK                  8
DELIVERY_DRIVER_ISSUE     8
MISSING_ITEM              6
WRONG_ITEM_RECEIVED       5
Name: count, dtype: int64